"""tests/harness/test_policy_registry.py -- TDD suite for .claude/policies/registry.yaml
(plan_26072506 Phase 4 -- Constitution/state SSOT and policy registry; schema_version 2,
review-cycle2 remediation of subagent-summary-0/1-20260725_213652).

Runner: stdlib `unittest`.

Invocation:
    python3 -m unittest tests.harness.test_policy_registry -v
    python3 -m unittest discover -s tests/harness -p 'test_*.py' -v

Design:
  - `registry.yaml`, `evidence_manifest.json`, and every fixture under
    tests/harness/fixtures/policy_registry/ are plain JSON text (a valid YAML 1.2 subset) --
    parsed here with the stdlib `json` module only. PyYAML is NOT a dependency of this module or
    anywhere else in this project.
  - Every lifecycle/evidence/structural/removal check is imported from scripts/policy_registry.py
    (the shared validator/auditor both this suite and a human running the CLI directly use) --
    there is no second, hand-duplicated checker class living only in this test file.
  - `AS_OF` below is a fixed, explicit `datetime.date` constant (matching the real registry's own
    last_reviewed_at), never the wall-clock `today` helper.
  - Every negative fixture is a deep-copy of `valid_baseline.yaml` with the SMALLEST field-level
    change that exercises the rule under test, generated by a one-off script (its provenance is
    documented in each fixture's neighboring test method) and asserted against the EXACT
    resulting violation reason_code SET (sorted list equality, or exact (code, policy_id/path)
    tuples where more than one code is a genuine mechanical consequence of that one field change
    -- e.g. renaming `policy_id` alone necessarily also breaks clause_id namespacing) -- never
    merely "some violation happened" (subagent-summary-1's brittle-test finding, cycle1 AND
    cycle2).
  - Evidence-path resolution in THESE fixture-level tests uses a per-call, auto-computed manifest
    (every real on-disk file an evidence entry cites gets its own freshly-computed correct
    sha256) rather than the committed `.claude/policies/evidence_manifest.json` -- this keeps
    fixtures hermetic and decoupled from that file's actual committed digests (which track
    registry.yaml's OWN evidence, not test fixtures). Tests that specifically exercise
    manifest/digest/symlink/escape mechanics build their OWN deliberate (non-auto) manifest --
    see Section H.
  - TestBaselineHeadLedger (moved to a companion module, see
    tests/harness/test_policy_registry_head_ledger.py) is the acceptance oracle for "did the
    migration preserve every HEAD invariant this policy replaced" -- an independently, HEAD-blob-
    anchored ledger, not a self-authored token list.
"""
from __future__ import annotations

import copy
import datetime
import json
import re
import subprocess
import sys
import tempfile
import unittest
from unittest import mock
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = REPO_ROOT / "scripts"
REGISTRY_PATH = REPO_ROOT / ".claude" / "policies" / "registry.yaml"
SCHEMA_PATH = REPO_ROOT / ".claude" / "schemas" / "policy-registry.schema.json"
EVIDENCE_MANIFEST_PATH = REPO_ROOT / ".claude" / "policies" / "evidence_manifest.json"
FIXTURES_DIR = REPO_ROOT / "tests" / "harness" / "fixtures" / "policy_registry"
REMOVAL_ARTIFACT_REL_PATH = "tests/harness/fixtures/policy_registry/removal_artifacts/valid_contract_e2e_green.json"
# gitignored scratch dir for dynamically-generated removal artifacts whose tree_sha256 must equal
# a freshly computed contract digest (cycle4 fix -- see docs.md/policy_registry.py module
# docstring "Removal eligibility": a static precomputed digest fixture would go stale on every
# future contract-file edit, so these two tests generate a matching artifact at run time instead
# of hand-maintaining one).
RUNTIME_SCRATCH_DIR = FIXTURES_DIR / "removal_artifacts" / "_runtime_scratch"

sys.path.insert(0, str(SCRIPTS_DIR))
import policy_registry as pr  # noqa: E402 -- the one shared validator/auditor, not re-implemented here

# Fixed, explicit as-of date -- matches registry.yaml's own last_reviewed_at (2026-07-25). Never
# the wall-clock `today` helper: this suite's pass/fail must not depend on the day it happens to run.
AS_OF = datetime.date(2026, 7, 25)

POLICY_ID_RE = pr.POLICY_ID_RE
CLAUSE_ID_RE = pr.CLAUSE_ID_RE


def _load_json(path: Path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


SCHEMA = _load_json(SCHEMA_PATH) if SCHEMA_PATH.is_file() else None


def _load_fixture(name: str) -> dict:
    return _load_json(FIXTURES_DIR / name)


def _load_registry() -> dict:
    return _load_json(REGISTRY_PATH)


def _schema_violations(doc: dict):
    return pr.schema_violations(doc, SCHEMA)


def _auto_manifest(doc: dict, repo_root: Path = REPO_ROOT, extra=()) -> dict:
    """Every real on-disk file an evidence.*.path or removal_evidence.path in `doc` cites gets
    its own freshly-computed, currently-correct sha256 -- see module docstring."""
    manifest: dict = {}
    for p in doc.get("policies", []):
        for e in (p.get("evidence") or []):
            if isinstance(e, dict) and isinstance(e.get("path"), str):
                full = repo_root / e["path"]
                if full.is_file():
                    manifest[e["path"]] = pr._sha256_file(full)
        removal = p.get("removal_evidence")
        if isinstance(removal, dict) and isinstance(removal.get("path"), str):
            full = repo_root / removal["path"]
            if full.is_file():
                manifest[removal["path"]] = pr._sha256_file(full)
    for rel in extra:
        full = repo_root / rel
        if full.is_file():
            manifest[rel] = pr._sha256_file(full)
    return manifest


def _lifecycle_violations(doc: dict, as_of: datetime.date = AS_OF, evidence_manifest: dict | None = None):
    if evidence_manifest is None:
        evidence_manifest = _auto_manifest(doc)
    return pr.evaluate_lifecycle(doc, as_of, repo_root=REPO_ROOT, evidence_manifest=evidence_manifest)


def _check_removal(doc: dict, policy_id: str):
    manifest = _auto_manifest(doc)
    policy = next(p for p in doc["policies"] if p["policy_id"] == policy_id)
    return pr.check_removal_eligibility(policy, repo_root=REPO_ROOT, evidence_manifest=manifest)


def _check_removal_full(doc: dict, policy_id: str, as_of: datetime.date = AS_OF):
    manifest = _auto_manifest(doc)
    selected = next(p for p in doc["policies"] if p["policy_id"] == policy_id)
    removal_rel = selected.get("removal_evidence", {}).get("path", REMOVAL_ARTIFACT_REL_PATH)
    tracked = copy.deepcopy(pr.load_tracked_index())
    tracked["entries"][removal_rel] = "0" * 40
    original = pr._git_staged_blob_sha
    def staged(root, rel):
        return "0" * 40 if rel == removal_rel else original(root, rel)
    with mock.patch.object(pr, "_git_staged_blob_sha", side_effect=staged):
        return pr.check_removal_full(doc, policy_id, as_of, SCHEMA, REPO_ROOT, manifest,
                                     tracked_index=tracked)


def _write_matching_removal_artifact(doc: dict, policy_id: str, as_of: datetime.date,
                                      corrupt_tree: bool = False):
    """Writes a temp removal-artifact JSON under RUNTIME_SCRATCH_DIR whose tree_sha256 exactly
    equals what check_removal_full will independently (re)compute for THIS doc/schema/
    evidence_manifest/claim_bindings/tracked_index -- see RUNTIME_SCRATCH_DIR's module-level
    comment for why this beats hand-maintaining a static precomputed digest fixture. Returns
    (rel_path, evidence_manifest_with_artifact_entry). When corrupt_tree, the artifact's
    tree_sha256 is deliberately wrong (a well-formed but non-matching 64-hex digest)."""
    RUNTIME_SCRATCH_DIR.mkdir(parents=True, exist_ok=True)
    artifact_path = RUNTIME_SCRATCH_DIR / f"artifact_{policy_id}.json"
    rel_path = str(artifact_path.relative_to(REPO_ROOT))
    selected = next(p for p in doc["policies"] if p["policy_id"] == policy_id)
    selected["removal_evidence"]["path"] = rel_path
    artifact_path.write_text("{}\n", encoding="utf-8")
    evidence_manifest = _auto_manifest(doc)
    claim_bindings = pr.load_claim_bindings()
    tracked_index = copy.deepcopy(pr.load_tracked_index())
    tracked_index["entries"][rel_path] = "0" * 40
    tree = pr.compute_contract_tree_sha256(
        doc, SCHEMA, evidence_manifest, claim_bindings, tracked_index, REPO_ROOT,
        selected_removal_artifact_path=rel_path)
    if corrupt_tree:
        tree = ("0" if tree[0] != "0" else "1") + tree[1:]
    artifact_path.write_text(json.dumps({
        "policy_id": policy_id, "result": "PASS", "as_of": as_of.isoformat(), "tree_sha256": tree,
    }), encoding="utf-8")
    evidence_manifest[rel_path] = pr._sha256_file(artifact_path)
    return rel_path, evidence_manifest


def _codes(violations) -> list:
    return sorted(v.reason_code for v in violations)


def _find(violations, reason_code, policy_id=None, clause_id=None, path=None):
    for v in violations:
        if v.reason_code != reason_code:
            continue
        if policy_id is not None and v.policy_id != policy_id:
            continue
        if clause_id is not None and v.clause_id != clause_id:
            continue
        if path is not None and v.path != path:
            continue
        return v
    return None


def _real_registry_lifecycle_violations():
    # Uses the COMMITTED evidence_manifest.json/tracked_index.json/claim_bindings.json
    # (evidence_manifest=None -> default load; tracked_index/claim_bindings explicitly loaded and
    # passed here) -- this exercises the SAME full check set the actual production `cmd_verify`
    # path always runs (cycle4: tracked-index ambient-git binding + clause-specific claim
    # bindings), unlike the fixture-level auto-manifest helper above (which never opts into either
    # -- see scripts/policy_registry.py module docstring "Tracked-index trust tiers" /
    # "Clause-specific claim bindings" for why that's a deliberate, safe default for fixtures).
    return pr.evaluate_lifecycle(_load_registry(), AS_OF, REPO_ROOT,
                                  tracked_index=pr.load_tracked_index(), claim_bindings=pr.load_claim_bindings())


def _real_registry_schema_violations():
    return _schema_violations(_load_registry())


# =============================================================================
# Section A -- registry.yaml exists, parses as plain JSON, and validates against the schema
# =============================================================================

class TestRegistryShape(unittest.TestCase):
    def test_schema_file_exists(self):
        self.assertTrue(SCHEMA_PATH.is_file(), f"missing {SCHEMA_PATH}")

    def test_registry_file_exists(self):
        self.assertTrue(REGISTRY_PATH.is_file(), f"missing {REGISTRY_PATH}")

    def test_evidence_manifest_file_exists(self):
        self.assertTrue(EVIDENCE_MANIFEST_PATH.is_file(), f"missing {EVIDENCE_MANIFEST_PATH}")

    def test_registry_is_valid_plain_json(self):
        doc = _load_registry()
        self.assertIsInstance(doc, dict, msg=f"registry.yaml did not parse to a mapping: {doc!r}")

    def test_registry_validates_against_schema(self):
        violations = _real_registry_schema_violations()
        self.assertEqual(violations, [], msg=f"schema violations: {[v.to_dict() for v in violations]}")

    def test_schema_version_is_2(self):
        doc = _load_registry()
        self.assertEqual(doc.get("schema_version"), 2)

    def test_registry_has_at_least_13_policies(self):
        doc = _load_registry()
        policies = doc.get("policies", [])
        self.assertGreaterEqual(len(policies), 13)

    def test_valid_baseline_fixture_has_zero_violations(self):
        doc = _load_fixture("valid_baseline.yaml")
        self.assertEqual(_schema_violations(doc), [])
        self.assertEqual(_lifecycle_violations(doc), [])

    def test_removal_eligible_fixture_has_zero_violations(self):
        doc = _load_fixture("valid_removal_eligible.yaml")
        self.assertEqual(_schema_violations(doc), [])
        self.assertEqual(_lifecycle_violations(doc), [])
        self.assertEqual(_check_removal(doc, "TEST_REMOVAL_ELIGIBLE"), [])


# =============================================================================
# Section B -- schema-level negative fixtures, exact reason_code
# =============================================================================

class TestSchemaLevelNegativeFixtures(unittest.TestCase):
    CASES = [
        ("neg_missing_remove_when.yaml", ["SCHEMA:SCHEMA_MISSING_REQUIRED_KEY:policies[0].remove_when"]),
        ("neg_invalid_status.yaml", ["SCHEMA:SCHEMA_ENUM_VIOLATION:policies[0].status"]),
        ("neg_unknown_property.yaml", ["SCHEMA:SCHEMA_UNKNOWN_PROPERTY:policies[0].not_a_real_field"]),
        ("neg_schema_version_mismatch.yaml", ["SCHEMA:SCHEMA_CONST_VIOLATION:schema_version"]),
        ("neg_review_missing_reviewer.yaml", ["SCHEMA:SCHEMA_MISSING_REQUIRED_KEY:policies[0].review.reviewer"]),
        ("neg_evidence_not_object.yaml", ["SCHEMA:SCHEMA_TYPE_MISMATCH:policies[0].evidence[0]"]),
    ]

    def test_each_case_has_the_exact_expected_reason_code_set(self):
        for fixture, expected_codes in self.CASES:
            with self.subTest(fixture=fixture):
                violations = _schema_violations(_load_fixture(fixture))
                self.assertEqual(sorted(v.reason_code for v in violations), sorted(expected_codes))

    def test_schema_violation_path_is_populated_not_only_embedded_in_reason_code(self):
        # subagent-summary-1 finding 6: Violation.path stayed null even though the field path
        # was embedded in the reason_code string.
        violations = _schema_violations(_load_fixture("neg_missing_remove_when.yaml"))
        self.assertEqual(violations[0].path, "policies[0].remove_when")

    def test_real_registry_has_zero_schema_violations(self):
        self.assertEqual(_real_registry_schema_violations(), [])


# =============================================================================
# Section C -- policy_id / clause_id pattern and namespacing (exact violation sets --
# subagent-summary-0 finding: neg_bad_policy_id_pattern.yaml genuinely cascades to a SECOND
# code (CLAUSE_ID_POLICY_MISMATCH) because the untouched clause_id no longer starts with the
# mutated policy_id -- the fix is asserting that TRUE exact pair, not `assertIn` on one code.)
# =============================================================================

class TestIdPatterns(unittest.TestCase):
    def test_duplicate_id_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_duplicate_policy_id.yaml"))
        codes = _codes(violations)
        self.assertEqual(codes, ["CLAUSE_ID_POLICY_MISMATCH", "CLAUSE_ID_POLICY_MISMATCH", "DUPLICATE_POLICY_ID"])
        self.assertIsNotNone(_find(violations, "DUPLICATE_POLICY_ID", policy_id="TEST_DUPLICATE_ID"))

    def test_real_registry_has_no_duplicate_ids(self):
        self.assertEqual([v for v in _real_registry_lifecycle_violations()
                           if v.reason_code == "DUPLICATE_POLICY_ID"], [])

    def test_bad_policy_id_pattern_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_bad_policy_id_pattern.yaml"))
        self.assertEqual(_codes(violations), ["BAD_POLICY_ID_PATTERN", "CLAUSE_ID_POLICY_MISMATCH"])
        self.assertIsNotNone(_find(violations, "BAD_POLICY_ID_PATTERN", policy_id="lowercase_bad_id"))

    def test_bad_clause_id_pattern_fixture_is_caught_exactly(self):
        # Renaming clause_id alone (leaving evidence.supports pointed at the OLD clause_id)
        # mechanically also orphans the (renamed) clause and dangles the evidence reference --
        # a real, precise 3-code consequence of one field mutation, not fixture sloppiness.
        violations = _lifecycle_violations(_load_fixture("neg_bad_clause_id_pattern.yaml"))
        self.assertEqual(_codes(violations),
                          ["BAD_CLAUSE_ID_PATTERN", "CLAUSE_WITHOUT_EVIDENCE", "EVIDENCE_DANGLING_CLAUSE_REF"])
        self.assertIsNotNone(_find(violations, "BAD_CLAUSE_ID_PATTERN", policy_id="TEST_BASE"))

    def test_real_registry_ids_all_match_pattern(self):
        violations = _real_registry_lifecycle_violations()
        self.assertEqual([v for v in violations
                           if v.reason_code in ("BAD_POLICY_ID_PATTERN", "BAD_CLAUSE_ID_PATTERN",
                                                 "CLAUSE_ID_POLICY_MISMATCH")], [])

    def test_real_registry_every_clause_id_matches_stable_shape(self):
        doc = _load_registry()
        for p in doc["policies"]:
            for c in p["clauses"]:
                with self.subTest(clause_id=c["clause_id"]):
                    self.assertRegex(c["clause_id"], CLAUSE_ID_RE.pattern)
                    self.assertTrue(c["clause_id"].startswith(f"{p['policy_id']}."))


class TestActivePolicyProvenance(unittest.TestCase):
    def test_both_provenance_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_both_provenance.yaml"))
        self.assertEqual(_codes(violations), ["PROVENANCE_VIOLATION"])

    def test_neither_provenance_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_neither_provenance.yaml"))
        self.assertEqual(_codes(violations), ["PROVENANCE_VIOLATION"])

    def test_real_registry_every_entry_has_exactly_one_provenance(self):
        violations = _real_registry_lifecycle_violations()
        self.assertEqual([v for v in violations if v.reason_code == "PROVENANCE_VIOLATION"], [])


class TestRemoveWhenSubstantive(unittest.TestCase):
    def test_repeated_character_filler_is_not_substantive(self):
        violations = _lifecycle_violations(_load_fixture("neg_lazy_remove_when.yaml"))
        self.assertEqual(_codes(violations), ["LAZY_REMOVE_WHEN"])

    def test_known_placeholder_word_is_not_substantive(self):
        violations = _lifecycle_violations(_load_fixture("neg_lazy_remove_when_placeholder.yaml"))
        self.assertEqual(_codes(violations), ["LAZY_REMOVE_WHEN"])

    def test_real_registry_remove_when_is_substantive(self):
        violations = _real_registry_lifecycle_violations()
        self.assertEqual([v for v in violations if v.reason_code == "LAZY_REMOVE_WHEN"], [])


# =============================================================================
# Section D -- lifecycle dates: syntax, ordering, chronology, 90-day (decoupled from review
# cadence), as-of consistency (cycle2: entirely new date-chronology layer + the two-independent-
# clocks fix -- see scripts/policy_registry.py module docstring)
# =============================================================================

class TestReviewShapeAndDates(unittest.TestCase):
    def test_bad_review_date_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_bad_review_date.yaml"))
        self.assertEqual(_codes(violations), ["REVIEW_SHAPE_VIOLATION"])

    def test_missing_review_reason_when_due_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_review_reason_missing.yaml"))
        self.assertEqual(_codes(violations), ["REVIEW_REASON_MISSING"])

    def test_real_registry_review_dates_are_iso8601_no_wallclock_compare(self):
        violations = _real_registry_lifecycle_violations()
        self.assertEqual([v for v in violations if v.reason_code == "REVIEW_SHAPE_VIOLATION"], [])


class TestReviewDueArithmetic(unittest.TestCase):
    def test_mismatched_due_date_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_review_due_arithmetic_mismatch.yaml"))
        self.assertEqual(_codes(violations), ["REVIEW_DUE_ARITHMETIC_MISMATCH"])

    def test_real_registry_next_review_due_equals_last_reviewed_plus_90_days(self):
        violations = _real_registry_lifecycle_violations()
        self.assertEqual([v for v in violations if v.reason_code == "REVIEW_DUE_ARITHMETIC_MISMATCH"], [])


class TestLastReproducedIsDateOrNull(unittest.TestCase):
    def test_literal_never_string_is_rejected(self):
        violations = _lifecycle_violations(_load_fixture("neg_last_reproduced_not_date.yaml"))
        self.assertEqual(_codes(violations), ["BAD_LAST_REPRODUCED_DATE"])

    def test_null_last_reproduced_is_accepted(self):
        violations = _lifecycle_violations(_load_fixture("valid_baseline.yaml"))
        self.assertEqual([v for v in violations if v.reason_code == "BAD_LAST_REPRODUCED_DATE"], [])

    def test_real_registry_last_reproduced_is_date_or_null(self):
        violations = _real_registry_lifecycle_violations()
        self.assertEqual([v for v in violations if v.reason_code == "BAD_LAST_REPRODUCED_DATE"], [])


class TestDateChronology(unittest.TestCase):
    """cycle2: entirely new -- added_at must itself be a valid date, and it/last_reproduced/
    review.last_reviewed_at must never be in the future relative to the explicit as_of, nor may
    added_at postdate last_reproduced or review.last_reviewed_at."""

    def test_malformed_added_at_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_bad_added_at.yaml"))
        self.assertEqual(_codes(violations), ["BAD_ADDED_AT"])

    def test_future_added_at_is_caught(self):
        # A single field mutation (added_at pushed to 2026-12-31) is mechanically ALSO after the
        # baseline's unchanged review.last_reviewed_at (2026-07-25) -- both are genuine, exact
        # consequences of the one change, not two independent defects bundled into one fixture.
        violations = _lifecycle_violations(_load_fixture("neg_future_added_at.yaml"))
        self.assertEqual(_codes(violations), ["ADDED_AFTER_REVIEW", "FUTURE_ADDED_AT"])

    def test_future_reproduction_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_future_reproduction.yaml"))
        self.assertEqual(_codes(violations), ["FUTURE_REPRODUCTION"])

    def test_reproduction_before_added_at_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_added_after_reproduction.yaml"))
        self.assertEqual(_codes(violations), ["ADDED_AFTER_REPRODUCTION"])

    def test_future_review_last_reviewed_at_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_future_review.yaml"))
        self.assertEqual(_codes(violations), ["FUTURE_REVIEW"])

    def test_added_at_after_review_last_reviewed_at_is_caught(self):
        violations = _lifecycle_violations(_load_fixture("neg_added_after_review.yaml"))
        self.assertEqual(_codes(violations), ["ADDED_AFTER_REVIEW", "FUTURE_ADDED_AT"])

    def test_real_registry_has_no_date_chronology_violations(self):
        violations = _real_registry_lifecycle_violations()
        chronology_codes = {"BAD_ADDED_AT", "FUTURE_ADDED_AT", "FUTURE_REPRODUCTION",
                             "ADDED_AFTER_REPRODUCTION", "FUTURE_REVIEW", "ADDED_AFTER_REVIEW"}
        self.assertEqual([v for v in violations if v.reason_code in chronology_codes], [])

    def test_no_wall_clock_access_in_policy_registry_module(self):
        src = (SCRIPTS_DIR / "policy_registry.py").read_text(encoding="utf-8")
        hits = pr.find_wallclock_calls(src)
        self.assertEqual(hits, [], msg=f"real wall-clock call(s) found: {hits}")

    def test_no_wall_clock_access_in_this_test_module(self):
        src = Path(__file__).read_text(encoding="utf-8")
        hits = pr.find_wallclock_calls(src)
        self.assertEqual(hits, [], msg=f"real wall-clock call(s) found: {hits}")


class Test90DayUnreproducedForcesCandidate(unittest.TestCase):
    """cycle2 fix: the reproduction-staleness clock's origin is last_reproduced when set, else
    added_at -- NOT an unconditional 'null last_reproduced == immediately stale' rule (cycle1's
    exact reported bug: a policy added TODAY with no reproduction was classified >=90-day-stale)."""

    def test_active_status_with_stale_reproduction_origin_is_caught(self):
        violations = _lifecycle_violations(_load_fixture("neg_unreproduced_90_day_not_candidate.yaml"))
        self.assertEqual(_codes(violations), ["UNREPRODUCED_90_DAY_NOT_CANDIDATE"])

    def test_recently_added_active_policy_with_null_reproduction_is_NOT_flagged(self):
        # cycle2 regression lock for subagent-summary-0's exact reproduction
        # ('new_never_reproduced_active' wrongly returning UNREPRODUCED_90_DAY_NOT_CANDIDATE').
        violations = _lifecycle_violations(_load_fixture("pos_recent_added_active_not_flagged.yaml"))
        self.assertEqual(violations, [])

    def test_candidate_status_with_null_last_reproduced_is_accepted(self):
        violations = _lifecycle_violations(_load_fixture("valid_baseline.yaml"))
        self.assertEqual([v for v in violations if v.reason_code == "UNREPRODUCED_90_DAY_NOT_CANDIDATE"], [])

    def test_real_registry_every_policy_is_candidate_pending_dated_reproduction(self):
        violations = _real_registry_lifecycle_violations()
        self.assertEqual([v for v in violations if v.reason_code == "UNREPRODUCED_90_DAY_NOT_CANDIDATE"], [])
        doc = _load_registry()
        non_candidate = [p["policy_id"] for p in doc["policies"]
                          if p["last_reproduced"] is None and p["status"] != "candidate"]
        self.assertEqual(non_candidate, [])


class TestAsOfConsistency(unittest.TestCase):
    """review.state (current/due/overdue) is a DETERMINISTIC, EXPLICIT function of next_review_due
    vs as_of alone (cycle2 fix: decoupled from reproduction staleness, which cycle1 conflated --
    see scripts/policy_registry.py module docstring 'TWO INDEPENDENT 90-day clocks'). A policy
    reviewed exactly on as_of is genuinely `current` for review purposes even when it is
    `candidate` (not yet reproduced) for status purposes."""

    def test_stale_review_claiming_current_is_caught_at_the_fixed_as_of(self):
        violations = _lifecycle_violations(_load_fixture("neg_as_of_mismatch_still_current.yaml"))
        self.assertEqual(_codes(violations), ["AS_OF_STATE_MISMATCH"])

    def test_same_fixture_is_genuinely_current_at_an_earlier_as_of(self):
        early = datetime.date(2026, 1, 15)
        doc = _load_fixture("neg_as_of_mismatch_still_current.yaml")
        violations = _lifecycle_violations(doc, as_of=early)
        self.assertEqual([v for v in violations if v.reason_code == "AS_OF_STATE_MISMATCH"], [])

    def test_real_registry_is_as_of_consistent_at_its_own_last_reviewed_date(self):
        violations = _real_registry_lifecycle_violations()
        self.assertEqual([v for v in violations if v.reason_code == "AS_OF_STATE_MISMATCH"], [])

    def test_real_registry_review_state_is_current_not_due(self):
        # Decoupled semantics (cycle2): reviewed exactly on as_of with next_review_due 90 days
        # out is genuinely `current`, independent of whether last_reproduced is null.
        doc = _load_registry()
        non_current = [p["policy_id"] for p in doc["policies"] if p["review"]["state"] != "current"]
        self.assertEqual(non_current, [])


# =============================================================================
# Section E -- status/retirement/removal-metadata closure
# =============================================================================

class TestStatusLifecycleClosure(unittest.TestCase):
    def test_invalid_status_fixture_is_caught_by_schema(self):
        self.assertNotEqual(_schema_violations(_load_fixture("neg_invalid_status.yaml")), [])

    def test_retirement_metadata_on_active_policy_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_retirement_metadata_on_active.yaml"))
        self.assertEqual(_codes(violations), ["RETIREMENT_METADATA_ON_LIVE_POLICY"])

    def test_removal_evidence_on_live_policy_is_caught(self):
        # cycle2 fix -- subagent-summary-1's exact reproduction: an active policy self-declaring
        # removal_evidence.status=contract_e2e_green passed with ZERO violations under cycle1.
        violations = _lifecycle_violations(_load_fixture("neg_active_with_removal_evidence.yaml"))
        self.assertEqual(_codes(violations), ["RETIREMENT_METADATA_ON_LIVE_POLICY", "UNREPRODUCED_90_DAY_NOT_CANDIDATE"])
        v = _find(violations, "RETIREMENT_METADATA_ON_LIVE_POLICY")
        self.assertIn("removal_evidence", v.message)

    def test_retired_without_reason_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_retired_without_reason.yaml"))
        self.assertEqual(_codes(violations), ["RETIRED_WITHOUT_REASON"])

    def test_dangling_supersede_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_dangling_supersede.yaml"))
        self.assertEqual(_codes(violations), ["DANGLING_SUPERSEDE"])

    def test_cycle_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_retired_cycle.yaml"))
        self.assertEqual(_codes(violations), ["SUPERSEDE_CYCLE", "SUPERSEDE_CYCLE"])
        cyclic_ids = {v.policy_id for v in violations if v.reason_code == "SUPERSEDE_CYCLE"}
        self.assertEqual(cyclic_ids, {"TEST_CYCLE_A", "TEST_CYCLE_B"})

    def test_real_registry_status_lifecycle_is_clean(self):
        violations = _real_registry_lifecycle_violations()
        closure_codes = {"STATUS_VIOLATION", "RETIREMENT_METADATA_ON_LIVE_POLICY",
                          "RETIRED_WITHOUT_REASON", "DANGLING_SUPERSEDE", "SUPERSEDE_CYCLE"}
        self.assertEqual([v for v in violations if v.reason_code in closure_codes], [])


class TestRemovalEligibility(unittest.TestCase):
    def test_non_retired_policy_is_not_removal_eligible(self):
        # cycle4 fixture cleanup (subagent-summary-1 finding 8): the former
        # neg_removal_not_eligible_not_retired.yaml was byte-IDENTICAL to valid_baseline.yaml --
        # a misleading duplicate file rather than a distinct fixture -- so this now reads
        # valid_baseline.yaml directly (it is already non-retired, which is all this test needs).
        doc = _load_fixture("valid_baseline.yaml")
        violations = _check_removal(doc, "TEST_BASE")
        self.assertEqual(_codes(violations), ["REMOVAL_NOT_ELIGIBLE"])

    def test_retired_without_contract_e2e_green_evidence_is_not_removal_eligible(self):
        doc = _load_fixture("neg_removal_not_eligible_no_evidence.yaml")
        violations = _check_removal(doc, "TEST_BASE")
        self.assertEqual(_codes(violations), ["REMOVAL_NOT_ELIGIBLE"])

    def test_retired_with_contract_e2e_green_evidence_is_removal_eligible(self):
        doc = _load_fixture("valid_removal_eligible.yaml")
        violations = _check_removal(doc, "TEST_REMOVAL_ELIGIBLE")
        self.assertEqual(violations, [])

    def test_removal_artifact_policy_id_mismatch_is_caught(self):
        doc = copy.deepcopy(_load_fixture("valid_removal_eligible.yaml"))
        doc["policies"][0]["policy_id"] = "TEST_SOMETHING_ELSE"
        doc["policies"][0]["clauses"][0]["clause_id"] = "TEST_SOMETHING_ELSE.C1"
        doc["policies"][0]["evidence"][0]["supports"] = ["TEST_SOMETHING_ELSE.C1"]
        violations = _check_removal(doc, "TEST_SOMETHING_ELSE")
        self.assertEqual(_codes(violations), ["REMOVAL_EVIDENCE_POLICY_ID_MISMATCH"])

    def test_removal_artifact_result_not_pass_is_caught(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo_root = Path(tmp)
            artifact_dir = repo_root / "artifacts"
            artifact_dir.mkdir()
            artifact_path = artifact_dir / "run.json"
            artifact_path.write_text(json.dumps({
                "policy_id": "TEST_REMOVAL_ELIGIBLE", "result": "FAIL",
                "as_of": "2026-07-25", "tree_sha256": "0" * 64,
            }), encoding="utf-8")
            manifest = {"artifacts/run.json": pr._sha256_file(artifact_path)}
            policy = {"policy_id": "TEST_REMOVAL_ELIGIBLE", "status": "retired",
                      "removal_evidence": {"status": "contract_e2e_green", "path": "artifacts/run.json"}}
            violations = pr.check_removal_eligibility(policy, repo_root=repo_root, evidence_manifest=manifest)
            self.assertEqual(_codes(violations), ["REMOVAL_EVIDENCE_RESULT_NOT_PASS"])

    def test_removal_artifact_bad_digest_field_is_caught(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo_root = Path(tmp)
            artifact_path = repo_root / "run.json"
            artifact_path.write_text(json.dumps({
                "policy_id": "TEST_REMOVAL_ELIGIBLE", "result": "PASS",
                "as_of": "2026-07-25", "tree_sha256": "not-a-real-digest",
            }), encoding="utf-8")
            manifest = {"run.json": pr._sha256_file(artifact_path)}
            policy = {"policy_id": "TEST_REMOVAL_ELIGIBLE", "status": "retired",
                      "removal_evidence": {"status": "contract_e2e_green", "path": "run.json"}}
            violations = pr.check_removal_eligibility(policy, repo_root=repo_root, evidence_manifest=manifest)
            self.assertEqual(_codes(violations), ["REMOVAL_EVIDENCE_DIGEST_FIELD_INVALID"])

    def test_no_real_registry_entry_is_currently_retired(self):
        doc = _load_registry()
        retired = [p["policy_id"] for p in doc["policies"] if p["status"] == "retired"]
        self.assertEqual(retired, [])


class TestRemovalFullContract(unittest.TestCase):
    """Removal runs full schema and full-registry lifecycle validation before selected-policy
    eligibility, so an unrelated registry/trust violation blocks removal."""

    def test_contract_tree_digest_binds_exact_removal_artifact_path(self):
        path_a = "docs/removal/relocated_a.json"
        path_b = "docs/removal/relocated_b.json"
        doc_a = _load_registry()
        doc_b = copy.deepcopy(doc_a)
        doc_a["policies"][0]["removal_evidence"] = {"path": path_a}
        doc_b["policies"][0]["removal_evidence"] = {"path": path_b}
        manifest_a = pr.load_evidence_manifest()
        manifest_b = copy.deepcopy(manifest_a)
        manifest_a[path_a] = "a" * 64
        manifest_b[path_b] = "a" * 64
        tracked_a = copy.deepcopy(pr.load_tracked_index())
        tracked_b = copy.deepcopy(tracked_a)
        tracked_a["entries"][path_a] = "a" * 40
        tracked_b["entries"][path_b] = "a" * 40
        digest_a = pr.compute_contract_tree_sha256(
            doc_a, SCHEMA, manifest_a, pr.load_claim_bindings(), tracked_a, REPO_ROOT,
            selected_removal_artifact_path=path_a)
        digest_b = pr.compute_contract_tree_sha256(
            doc_b, SCHEMA, manifest_b, pr.load_claim_bindings(), tracked_b, REPO_ROOT,
            selected_removal_artifact_path=path_b)
        self.assertNotEqual(digest_a, digest_b)

    def test_contract_tree_digest_includes_sibling_removal_artifact_identity(self):
        path_a = "docs/removal/a.json"
        path_b = "docs/removal/b.json"
        doc = _load_registry()
        doc["policies"][0]["removal_evidence"] = {"path": path_a}
        doc["policies"][1]["removal_evidence"] = {"path": path_b}
        manifest = pr.load_evidence_manifest()
        manifest[path_a] = "a" * 64
        manifest[path_b] = "b" * 64
        tracked = copy.deepcopy(pr.load_tracked_index())
        tracked["entries"][path_a] = "a" * 40
        tracked["entries"][path_b] = "b" * 40
        baseline = pr.compute_contract_tree_sha256(
            doc, SCHEMA, manifest, pr.load_claim_bindings(), tracked, REPO_ROOT,
            selected_removal_artifact_path=path_a)
        changed_manifest = copy.deepcopy(manifest)
        changed_tracked = copy.deepcopy(tracked)
        changed_manifest[path_b] = "c" * 64
        changed_tracked["entries"][path_b] = "c" * 40
        rebound = pr.compute_contract_tree_sha256(
            doc, SCHEMA, changed_manifest, pr.load_claim_bindings(), changed_tracked, REPO_ROOT,
            selected_removal_artifact_path=path_a)
        self.assertNotEqual(baseline, rebound)

    def test_tracked_index_and_claim_bindings_are_part_of_removal_lifecycle(self):
        doc = _load_registry()
        tracked = copy.deepcopy(pr.load_tracked_index())
        cited = "scripts/mem_watchdog.sh"
        self.assertIn(cited, tracked["entries"])
        tracked["entries"][cited] = "0" * 40
        violations = pr.check_removal_full(
            doc, "ARCH_WALL_VARIANT_LADDER", AS_OF, SCHEMA, REPO_ROOT,
            pr.load_evidence_manifest(), claim_bindings=pr.load_claim_bindings(),
            tracked_index=tracked, governed_prose_snapshot=pr.load_governed_prose_snapshot())
        self.assertIn("EVIDENCE_TRACKED_INDEX_DRIFT", _codes(violations))


    def test_self_cycle_elsewhere_in_the_registry_blocks_removal_of_the_selected_policy(self):
        doc = _load_fixture("neg_retired_cycle.yaml")
        violations = _check_removal_full(doc, "TEST_CYCLE_A")
        self.assertEqual(_codes(violations), ["SUPERSEDE_CYCLE", "SUPERSEDE_CYCLE"])

    def test_a_single_unrelated_registry_defect_blocks_removal_of_an_otherwise_eligible_policy(self):
        doc = copy.deepcopy(_load_fixture("valid_removal_eligible.yaml"))
        doc["policies"].append(copy.deepcopy(_load_fixture("neg_lazy_remove_when.yaml"))["policies"][0])
        violations = _check_removal_full(doc, "TEST_REMOVAL_ELIGIBLE")
        self.assertEqual(_codes(violations), ["LAZY_REMOVE_WHEN"])

    def test_schema_invalid_registry_blocks_removal_before_lifecycle_even_runs(self):
        doc = copy.deepcopy(_load_fixture("valid_removal_eligible.yaml"))
        del doc["policies"][0]["remove_when"]
        violations = _check_removal_full(doc, "TEST_REMOVAL_ELIGIBLE")
        self.assertEqual(_codes(violations), ["SCHEMA:SCHEMA_MISSING_REQUIRED_KEY:policies[0].remove_when"])

    def test_clean_registry_and_eligible_policy_is_fully_removal_eligible(self):
        doc = copy.deepcopy(_load_fixture("valid_removal_eligible.yaml"))
        rel_path, manifest = _write_matching_removal_artifact(doc, "TEST_REMOVAL_ELIGIBLE", AS_OF)
        doc["policies"][0]["removal_evidence"]["path"] = rel_path
        try:
            violations = _check_removal_full(doc, "TEST_REMOVAL_ELIGIBLE", AS_OF)
            self.assertEqual(violations, [])
        finally:
            (REPO_ROOT / rel_path).unlink(missing_ok=True)

    def test_removal_artifact_absent_from_tracked_index_is_rejected(self):
        doc = copy.deepcopy(_load_fixture("valid_removal_eligible.yaml"))
        rel_path, manifest = _write_matching_removal_artifact(doc, "TEST_REMOVAL_ELIGIBLE", AS_OF)
        try:
            tracked = copy.deepcopy(pr.load_tracked_index())
            tracked["entries"].pop(rel_path, None)
            violations = pr.check_removal_full(
                doc, "TEST_REMOVAL_ELIGIBLE", AS_OF, SCHEMA, REPO_ROOT, manifest,
                tracked_index=tracked)
            self.assertEqual([v.reason_code for v in violations], ["EVIDENCE_NOT_IN_TRACKED_INDEX"])
        finally:
            (REPO_ROOT / rel_path).unlink(missing_ok=True)

    def test_real_registry_verify_and_check_removal_command_line_agree_on_as_of_requirement(self):
        # documents that check-removal's CLI, like verify's, requires an explicit --as-of (see
        # TestCliHardening) -- this is an in-process sanity check, not a subprocess spawn.
        import inspect
        sig = inspect.signature(pr.check_removal_full)
        self.assertIn("as_of", sig.parameters)


class TestRemovalArtifactIdentityBinding(unittest.TestCase):
    """cycle4 fix (subagent-summary-1 finding 3): a removal artifact previously only had to be
    well-formed-64-hex/ISO-date shaped -- never bound to the ACTUAL tree/invocation it was
    checked against. check_removal_full now computes the real contract_tree_sha256 and requires
    the artifact's own tree_sha256/as_of to equal it exactly."""

    def test_staged_tree_mismatch_is_rejected(self):
        # Exact cycle3 reproduction #1: "the accepted fixture artifact's tree_sha256 differs from
        # staged tree ... check_removal_full() returned zero violations."
        doc = copy.deepcopy(_load_fixture("valid_removal_eligible.yaml"))
        rel_path, manifest = _write_matching_removal_artifact(doc, "TEST_REMOVAL_ELIGIBLE", AS_OF,
                                                                corrupt_tree=True)
        doc["policies"][0]["removal_evidence"]["path"] = rel_path
        try:
            violations = _check_removal_full(doc, "TEST_REMOVAL_ELIGIBLE", AS_OF)
            self.assertEqual([v.reason_code for v in violations], ["REMOVAL_EVIDENCE_TREE_MISMATCH"])
        finally:
            (REPO_ROOT / rel_path).unlink(missing_ok=True)

    def test_as_of_mismatch_against_the_artifacts_own_as_of_is_rejected(self):
        # Exact cycle3 reproduction #2: "requesting removal with --as-of 2026-07-26 still accepted
        # its as_of: 2026-07-25."
        doc = copy.deepcopy(_load_fixture("valid_removal_eligible.yaml"))
        rel_path, manifest = _write_matching_removal_artifact(doc, "TEST_REMOVAL_ELIGIBLE", AS_OF)  # as_of=2026-07-25
        doc["policies"][0]["removal_evidence"]["path"] = rel_path
        later = AS_OF + datetime.timedelta(days=1)  # 2026-07-26
        try:
            violations = _check_removal_full(doc, "TEST_REMOVAL_ELIGIBLE", later)
            # the tree hash also no longer matches at as_of=later (compute_contract_tree_sha256
            # does not depend on as_of, so the tree stays valid -- only the as_of binding should fire)
            self.assertEqual([v.reason_code for v in violations], ["REMOVAL_EVIDENCE_AS_OF_MISMATCH"])
        finally:
            (REPO_ROOT / rel_path).unlink(missing_ok=True)

    def test_compute_contract_tree_sha256_is_order_independent_and_deterministic(self):
        doc = _load_fixture("valid_baseline.yaml")
        schema = SCHEMA
        manifest = {"a": "1"}
        claim_bindings = {"x": "y"}
        tracked_index = {"z": "w"}
        h1 = pr.compute_contract_tree_sha256(doc, schema, manifest, claim_bindings, tracked_index, REPO_ROOT)
        h2 = pr.compute_contract_tree_sha256(doc, schema, manifest, claim_bindings, tracked_index, REPO_ROOT)
        self.assertEqual(h1, h2)
        self.assertRegex(h1, r"^[0-9a-f]{64}$")

    def test_compute_contract_tree_sha256_changes_when_registry_doc_changes(self):
        doc1 = _load_fixture("valid_baseline.yaml")
        doc2 = copy.deepcopy(doc1)
        doc2["policies"][0]["statement"] = doc2["policies"][0]["statement"] + " (mutated)"
        h1 = pr.compute_contract_tree_sha256(doc1, SCHEMA, {}, {}, {}, REPO_ROOT)
        h2 = pr.compute_contract_tree_sha256(doc2, SCHEMA, {}, {}, {}, REPO_ROOT)
        self.assertNotEqual(h1, h2)


# =============================================================================
# Section F -- structurally canonical clauses + manifest/digest-locked evidence-to-clause
# bindings + executable assertion_ids (cycle2 replaces cycle1's keyword-corroboration relevance
# entirely -- see scripts/policy_registry.py module docstring)
# =============================================================================

class TestClauseStructure(unittest.TestCase):
    def test_every_real_policy_has_a_nonempty_clauses_list(self):
        doc = _load_registry()
        missing = [p["policy_id"] for p in doc["policies"] if not p.get("clauses")]
        self.assertEqual(missing, [])

    def test_every_real_evidence_entry_is_an_object_with_path_supports_and_assertion_ids(self):
        doc = _load_registry()
        bad = []
        for p in doc["policies"]:
            for e in p.get("evidence") or []:
                if not (isinstance(e, dict) and "path" in e and "supports" in e and e["supports"]
                        and "assertion_ids" in e and e["assertion_ids"]):
                    bad.append((p["policy_id"], e))
        self.assertEqual(bad, [])

    def test_clause_without_evidence_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_clause_without_evidence.yaml"))
        self.assertEqual(_codes(violations), ["CLAUSE_WITHOUT_EVIDENCE"])
        self.assertIsNotNone(_find(violations, "CLAUSE_WITHOUT_EVIDENCE",
                                    policy_id="TEST_CLAUSE_WITHOUT_EVIDENCE",
                                    clause_id="TEST_CLAUSE_WITHOUT_EVIDENCE.C2"))

    def test_evidence_supports_dangling_clause_ref_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_evidence_dangling_clause_ref.yaml"))
        self.assertEqual(_codes(violations), ["CLAUSE_WITHOUT_EVIDENCE", "EVIDENCE_DANGLING_CLAUSE_REF"])

    def test_real_registry_every_clause_has_supporting_evidence(self):
        violations = _real_registry_lifecycle_violations()
        self.assertEqual([v for v in violations if v.reason_code == "CLAUSE_WITHOUT_EVIDENCE"], [])

    def test_real_registry_no_evidence_references_a_dangling_clause(self):
        violations = _real_registry_lifecycle_violations()
        self.assertEqual([v for v in violations if v.reason_code == "EVIDENCE_DANGLING_CLAUSE_REF"], [])


class TestImplementationEvidenceResolves(unittest.TestCase):
    def test_empty_evidence_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_empty_evidence.yaml"))
        self.assertEqual(_codes(violations), ["CLAUSE_WITHOUT_EVIDENCE", "EVIDENCE_EMPTY"])

    def test_absolute_path_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_evidence_untracked_absolute.yaml"))
        self.assertEqual(_codes(violations), ["EVIDENCE_UNTRACKED"])
        self.assertIsNotNone(_find(violations, "EVIDENCE_UNTRACKED", path="/etc/passwd"))

    def test_real_registry_every_evidence_path_resolves_and_is_tracked(self):
        violations = _real_registry_lifecycle_violations()
        bad = [v for v in violations if v.reason_code in (
            "EVIDENCE_UNTRACKED", "EVIDENCE_MISSING_FILE", "EVIDENCE_EMPTY", "EVIDENCE_PATH_ABSENT",
            "EVIDENCE_PATH_ESCAPES_REPO", "EVIDENCE_PATH_CONTAINS_SYMLINK", "EVIDENCE_DIGEST_MISMATCH")]
        self.assertEqual(bad, [], msg=f"unresolved/untracked/empty evidence: {[v.to_dict() for v in bad]}")

    def test_real_registry_every_assertion_id_resolves(self):
        violations = _real_registry_lifecycle_violations()
        bad = [v for v in violations if v.reason_code in (
            "EVIDENCE_ASSERTION_IDS_EMPTY", "EVIDENCE_ASSERTION_KIND_UNSUPPORTED",
            "EVIDENCE_ASSERTION_ID_NOT_FOUND")]
        self.assertEqual(bad, [], msg=f"unresolved assertion ids: {[v.to_dict() for v in bad]}")

    def test_real_registry_no_clause_relies_solely_on_prose_evidence(self):
        violations = _real_registry_lifecycle_violations()
        bad = [v for v in violations if v.reason_code == "CLAUSE_LACKS_EXECUTABLE_EVIDENCE"]
        self.assertEqual(bad, [])


# =============================================================================
# Section G -- evidence resolution mechanics: exact-manifest-listed, digest-locked, symlink- and
# escape-rejecting (cycle2 replaces cycle1's TRACKED_EVIDENCE_PREFIXES startswith() allowlist,
# which is exactly what let scripts/untracked_probe.py -- never reviewed, merely co-located under
# a tracked PREFIX -- resolve as if it were real evidence).
# =============================================================================

class TestEvidenceManifestResolution(unittest.TestCase):
    def _policy(self, path, assertion_ids=("x",)):
        return {"policy_id": "TEST_RES", "clauses": [{"clause_id": "TEST_RES.C1", "statement": "s"}],
                "evidence": [{"path": path, "supports": ["TEST_RES.C1"], "assertion_ids": list(assertion_ids)}]}

    def test_a_real_on_disk_file_not_listed_in_the_manifest_is_rejected_as_untracked(self):
        # The exact reviewer-reported exploit: cycle1's prefix-allowlist accepted ANY file that
        # merely started with a tracked prefix (e.g. scripts/untracked_probe.py); this file
        # genuinely exists on disk (scripts/doc_naming.py), but the manifest passed here simply
        # never lists it -- proof the fix checks manifest MEMBERSHIP, not path prefix/existence.
        self.assertTrue((REPO_ROOT / "scripts" / "doc_naming.py").is_file())
        violations = pr.evidence_structural_violations(
            [self._policy("scripts/doc_naming.py")], repo_root=REPO_ROOT, evidence_manifest={})
        self.assertIsNotNone(_find(violations, "EVIDENCE_UNTRACKED", path="scripts/doc_naming.py"))

    def test_symlink_at_any_path_component_is_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo_root = Path(tmp)
            real_target = repo_root / "real_dir"
            real_target.mkdir()
            real_file = real_target / "evidence.py"
            real_file.write_text("def f():\n    pass\n", encoding="utf-8")
            symlinked_dir = repo_root / "linked_dir"
            symlinked_dir.symlink_to(real_target, target_is_directory=True)
            rel = "linked_dir/evidence.py"
            manifest = {rel: pr._sha256_file(real_file)}
            violations = pr.evidence_structural_violations(
                [self._policy(rel)], repo_root=repo_root, evidence_manifest=manifest)
            self.assertIsNotNone(_find(violations, "EVIDENCE_PATH_CONTAINS_SYMLINK", path=rel))

    def test_leaf_symlink_is_also_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo_root = Path(tmp)
            real_file = repo_root / "real.py"
            real_file.write_text("def f():\n    pass\n", encoding="utf-8")
            link = repo_root / "link.py"
            link.symlink_to(real_file)
            manifest = {"link.py": pr._sha256_file(real_file)}
            violations = pr.evidence_structural_violations(
                [self._policy("link.py")], repo_root=repo_root, evidence_manifest=manifest)
            self.assertIsNotNone(_find(violations, "EVIDENCE_PATH_CONTAINS_SYMLINK", path="link.py"))

    def test_path_escape_via_dotdot_is_rejected(self):
        violations = pr.evidence_structural_violations(
            [self._policy("../outside_repo.py")], repo_root=REPO_ROOT, evidence_manifest={"../outside_repo.py": "x"})
        self.assertIsNotNone(_find(violations, "EVIDENCE_PATH_ESCAPES_REPO", path="../outside_repo.py"))

    def test_digest_mismatch_is_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo_root = Path(tmp)
            real_file = repo_root / "real.py"
            real_file.write_text("def f():\n    pass\n", encoding="utf-8")
            manifest = {"real.py": "0" * 64}  # deliberately wrong
            violations = pr.evidence_structural_violations(
                [self._policy("real.py")], repo_root=repo_root, evidence_manifest=manifest)
            self.assertIsNotNone(_find(violations, "EVIDENCE_DIGEST_MISMATCH", path="real.py"))

    def test_tampering_after_manifest_lock_is_caught(self):
        # A file that WAS reviewed (its original content's digest is what the manifest records)
        # but has since changed on disk must be rejected -- not silently re-trusted because the
        # path still resolves.
        with tempfile.TemporaryDirectory() as tmp:
            repo_root = Path(tmp)
            real_file = repo_root / "real.py"
            real_file.write_text("def original():\n    pass\n", encoding="utf-8")
            locked_digest = pr._sha256_file(real_file)
            real_file.write_text("def tampered():\n    pass\n", encoding="utf-8")
            manifest = {"real.py": locked_digest}
            violations = pr.evidence_structural_violations(
                [self._policy("real.py")], repo_root=repo_root, evidence_manifest=manifest)
            self.assertIsNotNone(_find(violations, "EVIDENCE_DIGEST_MISMATCH", path="real.py"))


class TestAssertionIdExtraction(unittest.TestCase):
    def test_python_extracts_top_level_functions_and_unittest_methods(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "sample.py"
            path.write_text(
                "import unittest\n\n"
                "SOME_CONST = 1\n\n"
                "def top_level():\n    pass\n\n"
                "class TestX(unittest.TestCase):\n"
                "    def test_one(self):\n        pass\n"
                "    def helper(self):\n        pass\n",
                encoding="utf-8",
            )
            ids = pr.extract_assertion_ids(path)
            self.assertEqual(ids, {"SOME_CONST", "top_level", "TestX.test_one"})

    def test_shell_extracts_functions_vars_and_long_options(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "sample.sh"
            path.write_text(
                "#!/bin/bash\nKEY_OK=0\nfoo() {\n  echo hi\n}\n"
                "case \"$1\" in\n  --topology) TOPO=\"$2\";;\nesac\n",
                encoding="utf-8",
            )
            ids = pr.extract_assertion_ids(path)
            self.assertEqual(ids, {"KEY_OK", "foo", "TOPO", "topology"})

    def test_yaml_extracts_anchored_keys_only(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "sample.yaml"
            path.write_text("top_key: 1\nnested:\n  inner_key: value\n# a comment: not a key line? actually is\n",
                             encoding="utf-8")
            ids = pr.extract_assertion_ids(path)
            self.assertIn("top_key", ids)
            self.assertIn("inner_key", ids)

    def test_markdown_extracts_heading_text_only_not_body_lines(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "sample.md"
            path.write_text("# Title\n\nSome body prose that is not a heading.\n\n## Sub Heading\n",
                             encoding="utf-8")
            ids = pr.extract_assertion_ids(path)
            self.assertEqual(ids, {"Title", "Sub Heading"})
            self.assertNotIn("Some body prose that is not a heading.", ids)

    def test_unsupported_extension_returns_none(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "sample.txt"
            path.write_text("irrelevant", encoding="utf-8")
            self.assertIsNone(pr.extract_assertion_ids(path))

    def test_empty_assertion_ids_is_caught(self):
        violations = pr.evidence_structural_violations(
            [{"policy_id": "TEST_RES", "clauses": [{"clause_id": "TEST_RES.C1", "statement": "s"}],
              "evidence": [{"path": "scripts/policy_registry.py", "supports": ["TEST_RES.C1"], "assertion_ids": []}]}],
            repo_root=REPO_ROOT,
            evidence_manifest={"scripts/policy_registry.py": pr._sha256_file(SCRIPTS_DIR / "policy_registry.py")})
        self.assertIsNotNone(_find(violations, "EVIDENCE_ASSERTION_IDS_EMPTY"))

    def test_substring_only_assertion_id_is_rejected_not_accepted(self):
        # subagent-summary-1: a substring match (e.g. inside a docstring/comment) must not count
        # -- 'xxzzzoraclexx' never appears as a REAL identifier anywhere in policy_registry.py.
        violations = pr.evidence_structural_violations(
            [{"policy_id": "TEST_RES", "clauses": [{"clause_id": "TEST_RES.C1", "statement": "s"}],
              "evidence": [{"path": "scripts/policy_registry.py", "supports": ["TEST_RES.C1"],
                             "assertion_ids": ["xxzzzoraclexx"]}]}],
            repo_root=REPO_ROOT,
            evidence_manifest={"scripts/policy_registry.py": pr._sha256_file(SCRIPTS_DIR / "policy_registry.py")})
        self.assertIsNotNone(_find(violations, "EVIDENCE_ASSERTION_ID_NOT_FOUND"))

    def test_korean_only_clause_still_requires_a_real_exact_assertion_id(self):
        # cycle2 fix retained: Korean-only clause text used to yield ZERO extracted keywords under
        # the OLD relevance mechanism (keyword corroboration), silently bypassing it entirely.
        # assertion_ids has no such language-dependent extraction step -- a real identifier is
        # required regardless of the clause statement's language. NOTE: this asserts only that
        # `evidence_structural_violations` alone (no claim_bindings passed) doesn't reject the
        # tuple on assertion-id-existence grounds -- it does NOT claim the identifier's mere
        # existence is sufficient to "support" this specific clause; see
        # TestClaimBindingEnforcement below (cycle4) for the fix that closes that exact gap
        # (subagent-summary-1 finding 2 / cycle3 finding 2).
        violations = pr.evidence_structural_violations(
            [{"policy_id": "TEST_RES", "clauses": [{"clause_id": "TEST_RES.C1", "statement": "한국어로만 적힌 조항"}],
              "evidence": [{"path": "scripts/policy_registry.py", "supports": ["TEST_RES.C1"],
                             "assertion_ids": ["evaluate_lifecycle"]}]}],
            repo_root=REPO_ROOT,
            evidence_manifest={"scripts/policy_registry.py": pr._sha256_file(SCRIPTS_DIR / "policy_registry.py")})
        self.assertEqual([v for v in violations if v.policy_id == "TEST_RES"], [])


class TestClaimBindingEnforcement(unittest.TestCase):
    """cycle4 fix (subagent-summary-1 finding 2 / cycle3 finding 2): a real, digest-matching,
    exact identifier's mere EXISTENCE in some cited file is not enough to "support" an arbitrary
    clause that happens to reference it -- `.claude/policies/claim_bindings.json` pre-registers
    the EXACT allowed (path, assertion_id) predicate set per clause_id; this is the mechanism that
    replaces the old (removed) `test_korean_only_clause_with_real_assertion_id_still_validates`,
    which explicitly locked the bypass in as accepted behavior."""

    def test_unrelated_korean_clause_backed_by_a_real_but_unbound_assertion_id_fails_claim_binding(self):
        # Exact cycle3 reproduction: a semantically unrelated Korean clause backed by
        # scripts/policy_registry.py:evaluate_lifecycle (a real, digest-matching identifier) --
        # this time WITH claim_bindings opted in, and evaluate_lifecycle registers a DIFFERENT
        # (path, assertion_id) pair as the only one this clause is allowed to cite.
        policies = [{"policy_id": "TEST_RES", "clauses": [{"clause_id": "TEST_RES.C1", "statement": "한국어로만 적힌 조항"}],
                     "evidence": [{"path": "scripts/policy_registry.py", "supports": ["TEST_RES.C1"],
                                    "assertion_ids": ["evaluate_lifecycle"]}]}]
        claim_bindings = {"bindings": {"TEST_RES.C1": [
            {"path": "scripts/policy_registry.py", "assertion_ids": ["schema_meta_violations"]},
        ]}}
        violations = pr.claim_binding_violations(policies, claim_bindings)
        self.assertEqual(len(violations), 1)
        self.assertEqual(violations[0].reason_code, "CLAIM_BINDING_MISMATCH")
        self.assertEqual(violations[0].policy_id, "TEST_RES")
        self.assertEqual(violations[0].clause_id, "TEST_RES.C1")

    def test_exactly_matching_binding_is_accepted(self):
        policies = [{"policy_id": "TEST_RES", "clauses": [{"clause_id": "TEST_RES.C1", "statement": "s"}],
                     "evidence": [{"path": "scripts/policy_registry.py", "supports": ["TEST_RES.C1"],
                                    "assertion_ids": ["evaluate_lifecycle"]}]}]
        claim_bindings = {"bindings": {"TEST_RES.C1": [
            {"path": "scripts/policy_registry.py", "assertion_ids": ["evaluate_lifecycle"]},
        ]}}
        self.assertEqual(pr.claim_binding_violations(policies, claim_bindings), [])

    def test_clause_id_absent_from_claim_bindings_is_out_of_scope_not_a_violation(self):
        # Fixture/test-only clause_ids (never registered in claim_bindings.json) must not be
        # spuriously flagged -- this is what keeps every OTHER fixture-based test in this suite
        # (none of which pass claim_bindings) working unaffected.
        policies = [{"policy_id": "TEST_RES", "clauses": [{"clause_id": "TEST_RES.C1", "statement": "s"}],
                     "evidence": [{"path": "scripts/policy_registry.py", "supports": ["TEST_RES.C1"],
                                    "assertion_ids": ["evaluate_lifecycle"]}]}]
        self.assertEqual(pr.claim_binding_violations(policies, {"bindings": {}}), [])

    def test_extra_undeclared_evidence_tuple_is_a_mismatch_not_silently_accepted(self):
        policies = [{"policy_id": "TEST_RES", "clauses": [{"clause_id": "TEST_RES.C1", "statement": "s"}],
                     "evidence": [{"path": "scripts/policy_registry.py", "supports": ["TEST_RES.C1"],
                                    "assertion_ids": ["evaluate_lifecycle", "schema_meta_violations"]}]}]
        claim_bindings = {"bindings": {"TEST_RES.C1": [
            {"path": "scripts/policy_registry.py", "assertion_ids": ["evaluate_lifecycle"]},
        ]}}
        violations = pr.claim_binding_violations(policies, claim_bindings)
        self.assertEqual([v.reason_code for v in violations], ["CLAIM_BINDING_MISMATCH"])

    def test_real_registry_every_bound_clause_exactly_matches_claim_bindings(self):
        doc = _load_registry()
        claim_bindings = pr.load_claim_bindings()
        violations = pr.claim_binding_violations(doc["policies"], claim_bindings)
        self.assertEqual(violations, [], msg=f"real registry evidence drifted from claim_bindings.json: "
                                              f"{[v.to_dict() for v in violations]}")

    def test_real_claim_bindings_covers_every_one_of_the_56_clause_ids_exactly(self):
        doc = _load_registry()
        registry_clause_ids = {c["clause_id"] for p in doc["policies"] for c in p.get("clauses", [])}
        claim_bindings = pr.load_claim_bindings()
        bound_ids = set(claim_bindings.get("bindings", {}))
        self.assertEqual(registry_clause_ids, bound_ids)
        self.assertEqual(len(registry_clause_ids), 56)

    def test_unsupported_kind_evidence_is_caught(self):
        gi = REPO_ROOT / ".gitignore"
        violations = pr.evidence_structural_violations(
            [{"policy_id": "TEST_RES", "clauses": [{"clause_id": "TEST_RES.C1", "statement": "s"}],
              "evidence": [{"path": ".gitignore", "supports": ["TEST_RES.C1"], "assertion_ids": ["x"]}]}],
            repo_root=REPO_ROOT, evidence_manifest={".gitignore": pr._sha256_file(gi)})
        self.assertIsNotNone(_find(violations, "EVIDENCE_ASSERTION_KIND_UNSUPPORTED", path=".gitignore"))


class TestClauseLacksExecutableEvidence(unittest.TestCase):
    def test_clause_supported_only_by_prose_is_caught(self):
        prose = FIXTURES_DIR / "prose_only_evidence_sample.md"
        violations = pr.clause_executable_evidence_violations([
            {"policy_id": "TEST_PROSE", "clauses": [{"clause_id": "TEST_PROSE.C1", "statement": "s"}],
             "evidence": [{"path": "tests/harness/fixtures/policy_registry/prose_only_evidence_sample.md",
                            "supports": ["TEST_PROSE.C1"], "assertion_ids": ["A stable heading anchor"]}]},
        ])
        self.assertIsNotNone(_find(violations, "CLAUSE_LACKS_EXECUTABLE_EVIDENCE", policy_id="TEST_PROSE",
                                    clause_id="TEST_PROSE.C1"))

    def test_clause_with_prose_plus_one_real_companion_is_not_flagged(self):
        violations = pr.clause_executable_evidence_violations([
            {"policy_id": "TEST_PROSE2", "clauses": [{"clause_id": "TEST_PROSE2.C1", "statement": "s"}],
             "evidence": [
                 {"path": "tests/harness/fixtures/policy_registry/prose_only_evidence_sample.md",
                  "supports": ["TEST_PROSE2.C1"], "assertion_ids": ["A stable heading anchor"]},
                 {"path": "scripts/policy_registry.py", "supports": ["TEST_PROSE2.C1"],
                  "assertion_ids": ["evaluate_lifecycle"]},
             ]},
        ])
        self.assertEqual(violations, [])

    def test_full_lifecycle_end_to_end_prose_only_fixture_is_caught_exactly(self):
        violations = _lifecycle_violations(_load_fixture("prose_only_clause_full_lifecycle.yaml"))
        self.assertEqual(_codes(violations), ["CLAUSE_LACKS_EXECUTABLE_EVIDENCE"])


class TestAdversarialMutationCycle1Reproduction(unittest.TestCase):
    """subagent-summary-0 finding 5 / subagent-summary-1: an unrelated-but-tracked-and-existing
    file (scripts/doc_naming.py, cited for an unrelated claim) must not count as evidence merely
    because the path resolves -- cycle1 fixed this with keyword corroboration (itself broken by
    a single appended keyword); cycle2 replaces that mechanism entirely with assertion_ids, which
    scripts/doc_naming.py cannot satisfy for a fabricated identifier ('x') that is not a real,
    exact function/variable name anywhere in that file.

    cycle4 note (subagent-summary-1 finding 8): neg_adversarial_mutation_cycle1.yaml deliberately
    reproduces cycle1's actual historical multi-field registry state (a specific incident, not a
    canonical single-mutation atom fixture) -- 3 of its 7 diff locations from valid_baseline.yaml
    are the mechanically-required policy_id/clause_id/supports-reference rename that comes with
    giving the fixture its own distinct policy_id, and the remaining 4 are the three SUBSTANTIVE
    field mutations this class's own test names call out. TestSingleMutationIsolation below adds
    the one-defect-per-fixture isolation this finding also asked for, as in-memory deep-copies of
    valid_baseline.yaml -- not a replacement for this historical-incident reproduction, which stays
    exactly as it is."""

    def test_reviewer_reported_unrelated_file_is_rejected_exactly(self):
        violations = _lifecycle_violations(_load_fixture("neg_adversarial_mutation_cycle1.yaml"))
        self.assertEqual(_codes(violations),
                          ["BAD_LAST_REPRODUCED_DATE", "EVIDENCE_ASSERTION_ID_NOT_FOUND", "LAZY_REMOVE_WHEN"])
        v = _find(violations, "EVIDENCE_ASSERTION_ID_NOT_FOUND", policy_id="TEST_ADVERSARIAL_MUTATION",
                  path="scripts/doc_naming.py")
        self.assertIsNotNone(v, msg=f"expected EVIDENCE_ASSERTION_ID_NOT_FOUND, got {_codes(violations)}")


class TestSingleMutationIsolation(unittest.TestCase):
    """cycle4 fix (subagent-summary-1 finding 8): isolates EACH of the three substantive defects
    neg_adversarial_mutation_cycle1.yaml bundles together, one at a time, as an in-memory
    deep-copy of valid_baseline.yaml with the SMALLEST possible single-field mutation -- exact
    (reason_code, policy_id, path) tuple asserted for each, not merely "some violation happened"."""

    def _baseline(self):
        return copy.deepcopy(_load_fixture("valid_baseline.yaml"))

    def test_last_reproduced_literal_never_string_in_isolation(self):
        doc = self._baseline()
        doc["policies"][0]["last_reproduced"] = "never"
        violations = _lifecycle_violations(doc)
        self.assertEqual([(v.reason_code, v.policy_id, v.path) for v in violations],
                          [("BAD_LAST_REPRODUCED_DATE", "TEST_BASE", "$.policies[TEST_BASE].last_reproduced")])

    def test_fabricated_assertion_id_in_isolation(self):
        doc = self._baseline()
        doc["policies"][0]["evidence"][0]["assertion_ids"] = ["xxzzzoraclexx"]
        violations = _lifecycle_violations(doc)
        self.assertEqual([(v.reason_code, v.policy_id, v.path) for v in violations],
                          [("EVIDENCE_ASSERTION_ID_NOT_FOUND", "TEST_BASE", "scripts/policy_registry.py")])

    def test_lazy_remove_when_in_isolation(self):
        doc = self._baseline()
        doc["policies"][0]["remove_when"] = "xxxxxxxxxxxxxxxxxxxx"
        violations = _lifecycle_violations(doc)
        self.assertEqual([(v.reason_code, v.policy_id, v.path) for v in violations],
                          [("LAZY_REMOVE_WHEN", "TEST_BASE", "$.policies[TEST_BASE].remove_when")])


class TestCycle5SemanticReviewerRegressions(unittest.TestCase):
    def test_shell_comment_cannot_supply_assertion_id(self):
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "evidence.sh"
            p.write_text("REAL=1\n# FAKE_ASSERTION=1\n# fake_fn() { :; }\n")
            ids = pr._shell_assertion_ids(p)
            self.assertIn("REAL", ids)
            self.assertNotIn("FAKE_ASSERTION", ids)
            self.assertNotIn("fake_fn", ids)

    def test_yaml_block_scalar_prose_cannot_supply_assertion_id(self):
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "evidence.yaml"
            p.write_text("real_key: ok\nnotes: |\n  fake_assertion_target: prose only\nnext_key: yes\n")
            ids = pr._yaml_assertion_ids(p)
            self.assertEqual(ids, {"real_key", "notes", "next_key"})

    def test_deep_json_recursion_is_structured_invalid_json(self):
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "deep.json"
            p.write_text("[" * 3000 + "]" * 3000)
            doc, err = pr.safe_load_json_object(p, "REGISTRY")
            self.assertIsNone(doc)
            self.assertEqual(err.reason_code, "REGISTRY_INVALID_JSON")

    def test_embedded_well_formed_unknown_id_is_not_silent(self):
        doc = _load_registry()
        violations = pr.citation_violations("자료apolicy:TOTALLY_FAKE_NONEXISTENT3 참고", doc)
        self.assertEqual([(v.reason_code, v.policy_id) for v in violations],
                         [("UNRESOLVED_CITATION", "TOTALLY_FAKE_NONEXISTENT3")])
        self.assertEqual(pr.citation_violations("xpolicy:BAD-ID", doc), [])


if __name__ == "__main__":
    unittest.main()
